name: Pull changes from GitHub
on:
  push:
    branches: [development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Update container
      run: docker-compose pull && docker-compose up -d
