name: Update Test Server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create directory != exist
      run: |
        if [ ! -d "/temp/wp-content" ]; then
          mkdir -p /temp/wp-content
        fi
    - name: Copy files to Droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./wp-content"
        target: "/tmp/wp-content"
    - name: Copy files to Docker container
      run: |
        docker cp /tmp/wp-content cp3402_wordpress_1:/var/www/html/wp-content/
